version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: plato-postgres
    environment:
      POSTGRES_DB: plato
      POSTGRES_USER: plato
      POSTGRES_PASSWORD: plato123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plato-network

  redis:
    image: redis:7-alpine
    container_name: plato-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - plato-network

  # Optional: Redis Commander for GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: plato-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - plato-network
    depends_on:
      - redis

  # Optional: pgAdmin for Database GUI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: plato-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@plato.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - plato-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  plato-network:
    driver: bridge